#!/usr/bin/env bash
VERSION=love-0.10.2-macosx-x64

if [ ! -d build/macos-love ]; then
    wget https://bitbucket.org/rude/love/downloads/$VERSION.zip -O build/macos-love.zip
    unzip build/macos-love.zip -d build/macos-love
fi

if [ -d build/o-macos ]; then
    rm -r build/o-macos
fi
mkdir -p build/o-macos/
cp -r build/macos-love/love.app build/o-macos/o.app
cp build/o.love build/o-macos/o.app/Contents/Resources/
cp manifests/Info.plist build/o-macos/o.app/Contents/Info.plist
